# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-16 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='Some text'),
        ),
    ]
